const CONTENTS = [
    {
        type: "nav",
        parentId: "topNavBar",
        itemId: "",
        itemClass: "",
        itemTitle: "Home",
        itemLink: "#",
        itemTarget: "",
        itemLinkClass: "",
        itemLinkId: "",
        order: 1
    },
    {
        type: "nav",
        parentId: "topNavBar",
        itemId: "",
        itemClass: "",
        itemTitle: "TV Shows",
        itemLink: "#",
        itemTarget: "",
        itemLinkClass: "",
        itemLinkId: "",
        order: 2
    },
    {
        type: "nav",
        parentId: "topNavBar",
        itemId: "",
        itemClass: "",
        itemTitle: "Movies",
        itemLink: "#",
        itemTarget: "",
        itemLinkClass: "",
        itemLinkId: "",
        order: 3
    },
    {
        type: "nav",
        parentId: "topNavBar",
        itemId: "",
        itemClass: "",
        itemTitle: "New & Popular",
        itemLink: "#",
        itemTarget: "",
        itemLinkClass: "",
        itemLinkId: "",
        order: 4
    },
    {
        type: "nav",
        parentId: "topNavBar",
        itemId: "",
        itemClass: "",
        itemTitle: "My List",
        itemLink: "#",
        itemTarget: "",
        itemLinkClass: "",
        itemLinkId: "",
        order: 5
    },
    {
        type: "dropdown",
        parentId: "genresDropDown",
        itemId: "",
        itemClass: "",
        itemTitle: "Action",
        itemLink: "#",
        itemTarget: "",
        itemLinkClass: "",
        itemLinkId: "",
        order: null,
    },
    {
        type: "dropdown",
        parentId: "genresDropDown",
        itemId: "",
        itemClass: "",
        itemTitle: "Comedy",
        itemLink: "#",
        itemTarget: "",
        itemLinkClass: "",
        itemLinkId: "",
        order: null,
    },
    {
        type: "dropdown",
        parentId: "genresDropDown",
        itemId: "",
        itemClass: "",
        itemTitle: "Drama",
        itemLink: "#",
        itemTarget: "",
        itemLinkClass: "",
        itemLinkId: "",
        order: null,
    },
    {
        type: "dropdown",
        parentId: "genresDropDown",
        itemId: "",
        itemClass: "",
        itemTitle: "Horror",
        itemLink: "#",
        itemTarget: "",
        itemLinkClass: "",
        itemLinkId: "",
        order: null,
    },
    {
        type: "dropdown",
        parentId: "genresDropDown",
        itemId: "",
        itemClass: "",
        itemTitle: "Romance",
        itemLink: "#",
        itemTarget: "",
        itemLinkClass: "",
        itemLinkId: "",
        order: null,
    },
    {
        type: "dropdown",
        parentId: "genresDropDown",
        itemId: "",
        itemClass: "",
        itemTitle: "Sci-Fi",
        itemLink: "#",
        itemTarget: "",
        itemLinkClass: "",
        itemLinkId: "",
        order: null,
    },
    {
        type: "dropdown",
        parentId: "genresDropDown",
        itemId: "",
        itemClass: "",
        itemTitle: "Thriller",
        itemLink: "#",
        itemTarget: "",
        itemLinkClass: "",
        itemLinkId: "",
        order: null,
    },
    {
        type: "nav",
        parentId: "footerLinks1",
        itemId: "",
        itemClass: "",
        itemTitle: "Audio And Subtitles",
        itemLink: "#",
        itemTarget: "",
        itemLinkClass: "",
        itemLinkId: "",
        order: null
    },
    {
        type: "nav",
        parentId: "footerLinks1",
        itemId: "",
        itemClass: "",
        itemTitle: "Media Center",
        itemLink: "#",
        itemTarget: "",
        itemLinkClass: "",
        itemLinkId: "",
        order: null
    },
    {
        type: "nav",
        parentId: "footerLinks1",
        itemId: "",
        itemClass: "",
        itemTitle: "Privacy",
        itemLink: "#",
        itemTarget: "",
        itemLinkClass: "",
        itemLinkId: "",
        order: null
    },
    {
        type: "nav",
        parentId: "footerLinks1",
        itemId: "",
        itemClass: "",
        itemTitle: "Contact Us",
        itemLink: "#",
        itemTarget: "",
        itemLinkClass: "",
        itemLinkId: "",
        order: null
    },
    {
        type: "nav",
        parentId: "footerLinks2",
        itemId: "",
        itemClass: "",
        itemTitle: "Audio Description",
        itemLink: "#",
        itemTarget: "",
        itemLinkClass: "",
        itemLinkId: "",
        order: null
    },
    {
        type: "nav",
        parentId: "footerLinks2",
        itemId: "",
        itemClass: "",
        itemTitle: "Investor Relation",
        itemLink: "#",
        itemTarget: "",
        itemLinkClass: "",
        itemLinkId: "",
        order: null
    },
    {
        type: "nav",
        parentId: "footerLinks2",
        itemId: "",
        itemClass: "",
        itemTitle: "Legal Notices",
        itemLink: "#",
        itemTarget: "",
        itemLinkClass: "",
        itemLinkId: "",
        order: null
    },


    {
        type: "nav",
        parentId: "footerLinks3",
        itemId: "",
        itemClass: "",
        itemTitle: "Help Center",
        itemLink: "#",
        itemTarget: "",
        itemLinkClass: "",
        itemLinkId: "",
        order: null
    },
    {
        type: "nav",
        parentId: "footerLinks3",
        itemId: "",
        itemClass: "",
        itemTitle: "Jobs",
        itemLink: "#",
        itemTarget: "",
        itemLinkClass: "",
        itemLinkId: "",
        order: null
    },
    {
        type: "nav",
        parentId: "footerLinks3",
        itemId: "",
        itemClass: "",
        itemTitle: "Cookie Preferencies",
        itemLink: "#",
        itemTarget: "",
        itemLinkClass: "",
        itemLinkId: "",
        order: null
    },

    {
        type: "nav",
        parentId: "footerLinks4",
        itemId: "",
        itemClass: "",
        itemTitle: "Gift Cards",
        itemLink: "#",
        itemTarget: "",
        itemLinkClass: "",
        itemLinkId: "",
        order: null
    },
    {
        type: "nav",
        parentId: "footerLinks4",
        itemId: "",
        itemClass: "",
        itemTitle: "Terms of Use",
        itemLink: "#",
        itemTarget: "",
        itemLinkClass: "",
        itemLinkId: "",
        order: null
    },
    {
        type: "nav",
        parentId: "footerLinks4",
        itemId: "",
        itemClass: "",
        itemTitle: "Corporate Infomation",
        itemLink: "#",
        itemTarget: "",
        itemLinkClass: "",
        itemLinkId: "",
        order: null
    },
    {
        type: "dropdown",
        parentId: "profileDropDown",
        itemId: "",
        itemClass: "",
        itemTitle: "User Profile",
        itemLink: "/profile.html",
        itemTarget: "",
        itemLinkClass: "",
        itemLinkId: "",
        order: null
    },
    {
        type: "dropdown",
        parentId: "profileDropDown",
        itemId: "",
        itemClass: "",
        itemTitle: "Settings",
        itemLink: "/settings.html",
        itemTarget: "",
        itemLinkClass: "",
        itemLinkId: "",
        order: null
    },
    {
        title: "The China Hustle",
        year: "2018",
        description: "Un documentario sulla truffa di Wall Street che coinvolge aziende cinesi, investitori e profitti sospetti.",
        cast: ["Dan David", "Matthew Wiechert"],
        imgSrc: "media5.webp",
        imdbLink: "https://www.imdb.com/title/tt7057300/",
        order: 1,
        parentId: "trendingNowCards",
        type: "card"
    },
    {
        title: "The Social Dilemma",
        year: "2020",
        description: "Un documentario che esplora l'impatto psicologico dei social media e le problematiche della privacy.",
        cast: ["Tristan Harris", "Jaron Lanier"],
        imgSrc: "media6.jpg",
        imdbLink: "https://www.imdb.com/title/tt11464826/",
        order: 2,
        parentId: "trendingNowCards",
        type: "card"
    },
    {
        title: "A.R.O.G",
        year: "2008",
        description: "Un film comico turco che racconta di un uomo trasportato indietro nel tempo fino all'età della pietra.",
        cast: ["Cem Yılmaz", "Özge Özberk"],
        imgSrc: "media7.webp",
        imdbLink: "https://www.imdb.com/title/tt1307062/",
        order: 3,
        parentId: "trendingNowCards",
        type: "card"
    },
    {
        title: "Yahşi Batı",
        year: "2010",
        description: "Un film comico ambientato nel Far West, in cui due agenti ottomani si trovano coinvolti in avventure esilaranti.",
        cast: ["Cem Yılmaz", "Ozan Güven"],
        imgSrc: "media8.webp",
        imdbLink: "https://www.imdb.com/title/tt1446147/",
        order: 4,
        parentId: "trendingNowCards",
        type: "card"
    },
    {
        title: "Connected",
        year: "2020",
        description: "Un documentario che esplora le connessioni nascoste che legano insieme le diverse parti del mondo.",
        cast: ["Latif Nasser"],
        imgSrc: "media9.jpg",
        imdbLink: "https://www.imdb.com/title/tt12950550/",
        order: 5,
        parentId: "trendingNowCards",
        type: "card"
    },
    {
        title: "Sherlock",
        year: "2010",
        description: "La versione moderna del celebre detective Sherlock Holmes e delle sue avventure risolvi-crimine.",
        cast: ["Benedict Cumberbatch", "Martin Freeman"],
        imgSrc: "media0.webp",
        imdbLink: "https://www.imdb.com/title/tt1475582/",
        order: 6,
        parentId: "trendingNowCards",
        type: "card"
    },
    {
        title: "American Factory",
        year: "2019",
        description: "Un documentario che esplora la cultura del lavoro americana e cinese dopo che una fabbrica è stata riaperta da investitori cinesi.",
        cast: ["Junming 'Jimmy' Wang", "Robert Allen"],
        imgSrc: "media1.jpg",
        imdbLink: "https://www.imdb.com/title/tt9351980/",
        order: 7,
        parentId: "trendingNowCards",
        type: "card"
    },
    {
        title: "The Good Place",
        year: "2016",
        description: "Una commedia esistenziale su una donna che cerca di diventare una persona migliore dopo la morte per guadagnare un posto in paradiso.",
        cast: ["Kristen Bell", "Ted Danson"],
        imgSrc: "media2.webp",
        imdbLink: "https://www.imdb.com/title/tt4955642/",
        order: 8,
        parentId: "trendingNowCards",
        type: "card"
    },
    {
        title: "Genius of the Modern World",
        year: "2016",
        description: "Una serie documentaria che esplora le vite di Karl Marx, Friedrich Nietzsche e Sigmund Freud.",
        cast: ["Bettany Hughes"],
        imgSrc: "media3.webp",
        imdbLink: "https://www.imdb.com/title/tt5844190/",
        order: 9,
        parentId: "trendingNowCards",
        type: "card"
    },
    {
        title: "Cuba and the Cameraman",
        year: "2017",
        description: "Un documentario che racconta la vita a Cuba attraverso gli occhi del regista nel corso di quattro decenni.",
        cast: ["Jon Alpert"],
        imgSrc: "media4.jpg",
        imdbLink: "https://www.imdb.com/title/tt7589524/",
        order: 10,
        parentId: "trendingNowCards",
        type: "card"
    },
    {
        title: "Narcos",
        year: "2015",
        description: "Una serie drammatica che racconta la storia dell'ascesa e della caduta del cartello di droga di Medellin guidato da Pablo Escobar.",
        cast: ["Wagner Moura", "Pedro Pascal"],
        imgSrc: "media13.jpg",
        imdbLink: "https://www.imdb.com/title/tt2707408/",
        order: 11,
        parentId: "watchItAgainCards",
        type: "card"
    },
    {
        title: "Breaking Bad",
        year: "2008",
        description: "Un insegnante di chimica malato di cancro si trasforma in un produttore di metanfetamina per garantire un futuro alla sua famiglia.",
        cast: ["Bryan Cranston", "Aaron Paul"],
        imgSrc: "media14.webp",
        imdbLink: "https://www.imdb.com/title/tt0903747/",
        order: 12,
        parentId: "watchItAgainCards",
        type: "card"
    },
    {
        title: "Explained",
        year: "2018",
        description: "Una serie documentaria che esplora vari argomenti sociali, politici e scientifici in maniera accessibile.",
        cast: ["Estelle Caswell", "Maria Bello"],
        imgSrc: "media15.jpg",
        imdbLink: "https://www.imdb.com/title/tt8005374/",
        order: 13,
        parentId: "watchItAgainCards",
        type: "card"
    },
    {
        title: "Rick and Morty",
        year: "2013",
        description: "Un anziano scienziato e suo nipote intraprendono avventure bizzarre e pericolose attraverso il multiverso.",
        cast: ["Justin Roiland", "Chris Parnell"],
        imgSrc: "media16.webp",
        imdbLink: "https://www.imdb.com/title/tt2861424/",
        order: 14,
        parentId: "watchItAgainCards",
        type: "card"
    },
    {
        title: "The White Helmets",
        year: "2016",
        description: "Un documentario che segue le vite dei soccorritori siriani che salvano vite nelle zone di conflitto.",
        cast: ["Khaled Farah", "Mohammed Farah"],
        imgSrc: "media17.jpg",
        imdbLink: "https://www.imdb.com/title/tt6073176/",
        order: 15,
        parentId: "watchItAgainCards",
        type: "card"
    },
    {
        title: "Spycraft",
        year: "2021",
        description: "Una serie documentaria che esplora i segreti delle tecnologie e delle tattiche di spionaggio utilizzate nel corso della storia.",
        cast: ["Dylan Berry"],
        imgSrc: "media18.jpg",
        imdbLink: "https://www.imdb.com/title/tt13613966/",
        order: 16,
        parentId: "watchItAgainCards",
        type: "card"
    },
    {
        title: "Better Call Saul",
        year: "2015",
        description: "Un prequel di Breaking Bad, che racconta la storia dell'avvocato Jimmy McGill, noto anche come Saul Goodman.",
        cast: ["Bob Odenkirk", "Jonathan Banks"],
        imgSrc: "media19.webp",
        imdbLink: "https://www.imdb.com/title/tt3032476/",
        order: 17,
        parentId: "watchItAgainCards",
        type: "card"
    },
    {
        title: "The Spy",
        year: "2019",
        description: "Un agente segreto israeliano si infiltra in Siria negli anni '60 per raccogliere informazioni di intelligence.",
        cast: ["Sacha Baron Cohen", "Noah Emmerich"],
        imgSrc: "media10.jpg",
        imdbLink: "https://www.imdb.com/title/tt5952634/",
        order: 18,
        parentId: "watchItAgainCards",
        type: "card"
    },
    {
        title: "Operation Varsity Blues: The College Admissions Scandal",
        year: "2021",
        description: "Un documentario che esplora lo scandalo delle ammissioni universitarie che ha coinvolto celebrità e famiglie ricche negli Stati Uniti.",
        cast: ["Matthew Modine"],
        imgSrc: "media11.jpg",
        imdbLink: "https://www.imdb.com/title/tt14111794/",
        order: 19,
        parentId: "watchItAgainCards",
        type: "card"
    },
    {
        title: "Tribes of Europa",
        year: "2021",
        description: "In un futuro post-apocalittico, delle tribù combattono per il controllo dell'Europa, dopo che una misteriosa catastrofe ha frammentato il continente.",
        cast: ["Henriette Confurius", "Oliver Masucci"],
        imgSrc: "media12.jpg",
        imdbLink: "https://www.imdb.com/title/tt9184986/",
        order: 20,
        parentId: "watchItAgainCards",
        type: "card"
    },
    {
        title: "Inside Bill's Brain: Decoding Bill Gates",
        year: "2019",
        description: "Un documentario che esplora la vita di Bill Gates, la sua carriera e i suoi progetti filantropici.",
        cast: ["Bill Gates"],
        imgSrc: "media20.jpg",
        imdbLink: "https://www.imdb.com/title/tt10822276/",
        order: 1,
        parentId: "newReleasesCards",
        type: "card"
    },
    {
        title: "Vikings",
        year: "2013",
        description: "Una serie drammatica che segue le avventure del leggendario guerriero vichingo Ragnar Lothbrok.",
        cast: ["Travis Fimmel", "Katheryn Winnick"],
        imgSrc: "media21.webp",
        imdbLink: "https://www.imdb.com/title/tt2306299/",
        order: 2,
        parentId: "newReleasesCards",
        type: "card"
    },
    {
        title: "How I Met Your Mother",
        year: "2005",
        description: "Una sitcom che racconta la storia di Ted Mosby mentre cerca la donna della sua vita, narrando ai suoi figli come ha conosciuto la loro madre.",
        cast: ["Josh Radnor", "Jason Segel", "Cobie Smulders"],
        imgSrc: "media22.webp",
        imdbLink: "https://www.imdb.com/title/tt0460649/",
        order: 3,
        parentId: "newReleasesCards",
        type: "card"
    },
    {
        title: "Dream Big: Engineering Our World",
        year: "2017",
        description: "Un documentario che celebra le meraviglie dell'ingegneria, esplorando come la tecnologia sta cambiando il nostro mondo.",
        cast: ["Jeff Bridges"],
        imgSrc: "media23.webp",
        imdbLink: "https://www.imdb.com/title/tt6236404/",
        order: 4,
        parentId: "newReleasesCards",
        type: "card"
    },
    {
        title: "Our Planet",
        year: "2019",
        description: "Una serie documentaria che esplora le meraviglie naturali della Terra e l'impatto dell'umanità sul pianeta.",
        cast: ["David Attenborough"],
        imgSrc: "media24.jpg",
        imdbLink: "https://www.imdb.com/title/tt9253866/",
        order: 5,
        parentId: "newReleasesCards",
        type: "card"
    },
    {
        title: "Modern Family",
        year: "2009",
        description: "Una commedia che segue le vite di tre famiglie interconnesse e tutte le loro dinamiche stravaganti.",
        cast: ["Ed O'Neill", "Sofía Vergara", "Julie Bowen"],
        imgSrc: "media25.webp",
        imdbLink: "https://www.imdb.com/title/tt1442437/",
        order: 6,
        parentId: "newReleasesCards",
        type: "card"
    },
    {
        title: "Leyla and Mecnun",
        year: "2011",
        description: "Una serie comica e surreale che reinterpreta la leggenda dell'amore impossibile tra Leyla e Mecnun.",
        cast: ["Ali Atay", "Melis Birkan"],
        imgSrc: "media26.webp",
        imdbLink: "https://www.imdb.com/title/tt1848220/",
        order: 7,
        parentId: "newReleasesCards",
        type: "card"
    },
    {
        title: "History 101",
        year: "2020",
        description: "Una serie documentaria che utilizza grafica e animazioni per raccontare storie di scienza, tecnologia e cultura.",
        cast: ["Natalie Silverman"],
        imgSrc: "media27.jpg",
        imdbLink: "https://www.imdb.com/title/tt12229108/",
        order: 8,
        parentId: "newReleasesCards",
        type: "card"
    },
    {
        title: "Peaky Blinders",
        year: "2013",
        description: "Un dramma storico che segue le vicende di una famiglia criminale di Birmingham dopo la Prima Guerra Mondiale.",
        cast: ["Cillian Murphy", "Helen McCrory"],
        imgSrc: "media28.jpg",
        imdbLink: "https://www.imdb.com/title/tt2442560/",
        order: 9,
        parentId: "newReleasesCards",
        type: "card"
    },
    {
        title: "My Octopus Teacher",
        year: "2020",
        description: "Un documentario che racconta la straordinaria amicizia tra un cineasta e un polpo in una foresta di alghe del Sudafrica.",
        cast: ["Craig Foster"],
        imgSrc: "media29.jpg",
        imdbLink: "https://www.imdb.com/title/tt12888462/",
        order: 10,
        parentId: "newReleasesCards",
        type: "card"
    },
    {
        title: "Magic for Humans",
        year: "2018",
        description: "Un divertente show di magia in cui il prestigiatore Justin Willman combina umorismo e magia nelle interazioni di tutti i giorni.",
        cast: ["Justin Willman"],
        imgSrc: "media30.jpg",
        imdbLink: "https://www.imdb.com/title/tt8593904/",
        order: 21,
        parentId: "trendingNowCards",
        type: "card"
    },
    {
        title: "The Most Unknown",
        year: "2018",
        description: "Un documentario che segue scienziati di diverse discipline mentre esplorano i misteri fondamentali del nostro universo.",
        cast: ["Jennifer L. Macalady", "Rachel L. Smith"],
        imgSrc: "media31.webp",
        imdbLink: "https://www.imdb.com/title/tt7966984/",
        order: 21,
        parentId: "watchItAgainCards",
        type: "card"
    },
    {
        title: "The Last Dance",
        year: "2020",
        description: "Una serie documentaria che racconta la carriera di Michael Jordan, in particolare durante la stagione 1997-1998 dei Chicago Bulls.",
        cast: ["Michael Jordan", "Scottie Pippen", "Dennis Rodman"],
        imgSrc: "media32.jpg",
        imdbLink: "https://www.imdb.com/title/tt8420184/",
        order: 11,
        parentId: "newReleasesCards",
        type: "card"
    }
];
